- name: Deploy the project
  hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/project.yml

  roles:

    - role: common
      common_fix_sudoers: yes
      common_sudoers_file_to_remove: debian-cloud-init
      tags: ['base', ]

    - role: postgres-install

    - role: nginx
      nginx_delete_default_site: yes
      nginx_catchall_enable: yes
      nginx_override_conf: |
        server_names_hash_bucket_size 128;

    - role: acme-nginx
      acme_domains:
        - "{{ host_public_domain_name }}"
      # acme_multi_domains: "{{ host_acme_multi_domains }}"
      when: host_enable_acme_ssl|default(False)
      tags: ['acme', ]

    - role: django

    - role: django-deploy
      become: yes
      become_user: "{{ django_user }}"

    # - role: nginx-redirect
    #   nginx_redirects:
    #     - from: "{{ host_public_domain_name_redirect_from }}"
    #       to: "{{ host_public_domain_name }}"
    #       ssl: yes
    #   when: host_is_the_real_thing
